version: "3.7"

services:
  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
  src:
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - ./:/src
    command: >
      sh -c "python manage.py runserver 0.0.0.0:9000"
    environment:
      - DB_HOST=db
      - DB_NAME=Share_it_db
      - DB_USER=postgres
      - DB_PASS=root
    depends_on:
      - db
      - redis
  db:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=Share_it_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - REDIS_HOST=redis
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    container_name: shareapp-pgadmin #you can change this
    depends_on:
      - db
    ports:
      - "5052:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
