# Generated by Django 2.2.13 on 2020-08-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='no-img.png', upload_to='media/profile_pics'),
        ),
    ]
