# Generated by Django 2.2.13 on 2020-06-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='no-img.png', null=True, upload_to='media/profile_pics'),
        ),
    ]
