# Generated by Django 2.2.13 on 2020-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
