# Generated by Django 2.2.13 on 2020-06-27 15:42

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pic',
        ),
        migrations.AlterField(
            model_name='itemimagemodel',
            name='image',
            field=models.ImageField(upload_to=main.models.upload_path),
        ),
    ]
