# Generated by Django 2.2.13 on 2020-08-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_itemmodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='state',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
