# Generated by Django 2.2.13 on 2020-08-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200807_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='no-img.png', upload_to='media/profile_pics'),
        ),
    ]
