# Generated by Django 2.2.13 on 2020-06-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200627_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='term_and_conditions',
            field=models.TextField(default='note'),
            preserve_default=False,
        ),
    ]
